### ISSUE TITLE
How disallow user to insert unlisted html tags?

### ISSUE THREAD

**Issue by kurtiev** [stevermeister/ngWig#101]
`<div  ng-wig="textModel" buttons="bold, italic, link, list1, list2, formats"</div>`
On copy paste event of any html documents, all img <img> etc. html tags will inserted into. How it dissalow?

**Comment by stevermeister** [comment]
@kurtiev  you could overwrite **onPaste** callback for your needs

**Comment by kurtiev** [comment]
Oh, sorry i'm forgotten close this issue. I decide replace all tags on copy paste event and rewrite a little code in ng-wig.js. Line 80
`$element.on('paste', function(e) {
          var presentValue = $element.html();
          scope.onPaste(e, $element.html()).then(function(val) {
              var regex = /(<([^>]+)>)/ig;
              presentValue += val.replace(regex, "");
            $element.html(presentValue);
          })
        });`

This is save existing text with needed tags
