### ISSUE TITLE
Add buttons for insertimage and justifycenter/justifyfull/justifyleft/justifyright

### ISSUE THREAD

**Issue by IuliaDobra** [stevermeister/ngWig#102]

**Comment by stevermeister** [comment]
@IuliaDobra ,
you could create plugin for it, right?

**Comment by IuliaDobra** [comment]
@stevermeister I added the buttons on my local machine after I downloaded the source files from the website, I don't know if i can contribute to the repo, I could add them myself here, too.

**Comment by stevermeister** [comment]
could you have a look at examples?
https://github.com/stevermeister/ngWig/tree/master/src/javascript/app/plugins

and after [create a pull request](https://help.github.com/articles/creating-a-pull-request/) to contribute to this repo.

**Comment by bampakoa** [comment]
@IuliaDobra if you want to give a hand on this, ping me, and I'll be happy to help.

**Comment by IuliaDobra** [comment]
@bampakoa yes, i would need some help.

**Comment by bampakoa** [comment]
@IuliaDobra for justification you could use method **addStandardButton** of **ngWigToolbarProvider**.

For example:

`ngWigToolbarProvider.addStandardButton('justify-left', 'Justify left', 'justifyLeft', 'fa-align-left');`

The same is valid for the rest of justification buttons.

**Comment by IuliaDobra** [comment]
Did you got my last e-mail? I used that for justification

**Comment by bampakoa** [comment]
@IuliaDobra I got your email but you did not mention anything about justification. Nevertheless, if you have used it that way, you are ok!
