### ISSUE TITLE
Clear formatting button

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngWig#103]
Hi,

I was just thinking for adding a button to clear formatting of a selected piece of text. What's your opinion?

Thanks!

**Comment by stevermeister** [comment]
Hi Aristeidis ,

not sure about core functionality but like plugin it would be really great to have

**Comment by bampakoa** [comment]
Hi Stepan

Why not a core functionality? I mean, since it refers to a function that overwrites the result of all other buttons, imo it should be there.

**Comment by stevermeister** [comment]
> it refers to a function that overwrites the result of all other buttons

no, it does not. You just make changes with content, no?

**Comment by bampakoa** [comment]
It actually removes all styles (e.g. Bold, Italic) and leaves only text.

**Comment by stevermeister** [comment]
but do you want to do it though buttons?

**Comment by bampakoa** [comment]
Initially yes. Do you have some other way in mind?

**Comment by stevermeister** [comment]
yes, sure.
just a regular expression, or even something more clever. 

http://stackoverflow.com/a/822486/274500

**Comment by bampakoa** [comment]
How about: `ngModelController.$setViewValue($element.text());`

**Comment by stevermeister** [comment]
yes, could be.   :)
so we don't need to have dependancy on buttons.

**Comment by bampakoa** [comment]
Don't we need a button to execute the **Clear formatting** command?

**Comment by stevermeister** [comment]
could you make PR for it?

**Comment by bampakoa** [comment]
Yes of course!

**Comment by bampakoa** [comment]
How about having a checkbox that will toggle between HTML mode and Plain text mode?

**Comment by stevermeister** [comment]
I think it's not the best solution.
What the reason to use WYSIWYG for plain text? may be just textarea would be enough?

**Comment by bampakoa** [comment]
The reason is: 
I recently faced a problem where the user pasted text from a Microsoft Word document that it had styles in it like line breaks and paragraphs. Those styles were not visible during editing using ngWig. 

When the user previewed the text, in another angular view that I have created, the styles were visible and the text was not properly formatted as during editing.

**Comment by stevermeister** [comment]
yes, it's well known issue, but I think just a checkbox does not help

**Comment by bampakoa** [comment]
In my fork, I added a button that clears all styling from the content and leaves only plain text. Do you have any other suggestion?

**Comment by stevermeister** [comment]
but what if you do want to copy the styles?

**Comment by bampakoa** [comment]
What do you mean? Can you describe a case?

**Comment by stevermeister** [comment]
I would like to copy text with styles, what do you want me to explain?
Do you suggest always to clean them up?

**Comment by bampakoa** [comment]
For that you describe,imo, I would make an extra button plugin to copy styles.

**Comment by stevermeister** [comment]
but could you please take a look at existing WYSIWYG editors? they just paste content with styles

**Comment by bampakoa** [comment]
As far as I know, CKEditor has a similar button called **Paste as plain text**.

**Comment by stevermeister** [comment]
ok, let's create such button.
but default one still keep with styles

**Comment by bampakoa** [comment]
Totally agree, the default will be with styles. I will make a PR for you.

**Comment by stevermeister** [comment]
:+1:

**Comment by bampakoa** [comment]
@stevermeister should I wait for release 3 to create the PR?

**Comment by stevermeister** [comment]
@bampakoa, I think it's not a lot of changes for plugins, but yes, probably it's better to wait.

also you could join code review for it 
https://github.com/stevermeister/ngWig/pull/105

**Comment by bampakoa** [comment]
In replacement of #110
