### ISSUE TITLE
Add ability to use ng-change

### ISSUE THREAD

**Issue by bolelamx** [stevermeister/ngWig#108]

**Comment by stevermeister** [comment]
looks like it works :)

**Comment by herrwalter** [comment]
Sorry, doesnt work here either

**Comment by stevermeister** [comment]
please update to **v3.0.0-rc2**
still only release candidate, but a lot was fixed since **2.3.7**
let me know if it still does not work

**Comment by herrwalter** [comment]
v3.0.0-rc2 is not released yet.. only rc1 is released and its not working on that tag either

**Comment by stevermeister** [comment]
actually it should.
please check an example
https://plnkr.co/edit/gSh3gTABfm3OGRAPcyxQ?p=preview

**Comment by herrwalter** [comment]
He is unable to find the tag.
![image](https://cloud.githubusercontent.com/assets/2805458/15387821/4d305690-1daf-11e6-9808-321d1424d044.png)

When i update to master it all works find. Though i'd like to see a tag/release so I can depend on the current state of the master.

**Comment by stevermeister** [comment]
true, bower does not support it 
ok, let me release 3.0 then.

**Comment by stevermeister** [comment]
enjoy version 3.0.1 in bower and npm

**Comment by herrwalter** [comment]
I thank you! _o_
