### ISSUE TITLE
Access ng-model attribute from plugins

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngWig#114]
It would be very nice, to have access to the **ng-model** attribute of the editor, from inside a plugin. In that way, the plugin could alter the value of the model anytime it needs to, thus giving the opportunity of extending the plugin collection.

**Comment by stevermeister** [comment]
💯

**Comment by bampakoa** [comment]
Please feel free for anyone to comment on potential ways of implementing this feature.
