### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngWig#115]
I think that unit tests should not be absent from the source code. I am willing to make a PR for this and @stevermeister we should notify the other plugin writers to act so.

**Comment by stevermeister** [comment]
@bampakoa I would love to see unit tests, but never have time for it. If you could help me with it it would be great. Only one thing - I thinking about moving to webpack. May be we could do webapck migration first?

**Comment by bampakoa** [comment]
Agree for migrating to webpack first. Have you done any work on that yet?

**Comment by bampakoa** [comment]
@stevermeister any news on the webpack integration?

**Comment by stevermeister** [comment]
not yet :(
did not have time for it

**Comment by bampakoa** [comment]
I can have a look on webpack, if that is ok with you.

**Comment by stevermeister** [comment]
may be we could write tests with grunt. 
test are more important than webpack migration. and still not sure about the gain.

**Comment by bampakoa** [comment]
closing in favor of #129
