### ISSUE TITLE
Incompatible with angular-sanitize

### ISSUE THREAD

**Issue by timbrown81** [stevermeister/ngWig#119]
The editor appears to be incompatible with angular-sanitize.  

To demonstrate, I forked your basic demo and added the <script> for angular-sanitize.  I then added the dependency and injected the $sca service.  The final step prevents the editor from being rendered and throws the following error: 

[$injector:unpr] http://errors.angularjs.org/1.5.0/$injector/unpr?p0=%24scaProvider%20%3C-%20%24sca 

Plunker: https://plnkr.co/edit/yJk4gV1Ymt4rLnBd30Db

**Comment by bampakoa** [comment]
@timbrown81 your issue description is incomplete. There is a missing piece at the end of it. :smile:

**Comment by timbrown81** [comment]
Sorry, I figured out my problem and didn't intend to post the issue.
