### ISSUE TITLE
Can't get focused using keyboard tab key

### ISSUE THREAD

**Issue by sajithk** [stevermeister/ngWig#130]
The editor is not focused when I used keyboard tab key to navigate through my form. I found that 
tabindex is set to -1 in ng-wig/views/ng-wig.html tempate in ngWig\dist\ng-wig.js.

**Comment by bampakoa** [comment]
@sajithk This is something that has been reported also in a previous issue #13 . I think that changing just the tabindex should not be enough in situations with multiple editors. Do you have any ideas to suggest?

Thanks for your issue!

**Comment by alainib** [comment]
i have multiple ng-wig textarea and want to switch for one to the next with tab. how to do this please ?

**Comment by stevermeister** [comment]
@bampakoa probably we could create something with tabIndex, here? 
(like https://codepen.io/tjacobdesign/pen/qpxyh)

**Comment by bampakoa** [comment]
BTW, @alainib nice catch for the tabindex!
