### ISSUE TITLE
Plugins don't work in IE in version 3.0.1

### ISSUE THREAD

**Issue by nonblocking** [stevermeister/ngWig#132]
In the latest version (3.0.1) the plugins (e.g. format) don't work in IE10+11, because of the _disabled_ attribute on the _ng-wig-plugin_ element. IE disables all form elements within an element with a disabled attribute.

It can easily be fixed by naming the attribute "data-disabled" instead of "disabled" (in _ng-wig-plugin-adapter.component.js_).

And could you please release a new version? 3.0.1 is broken anyway, because of the typo in the template (editMode instead of edit-mode), which is already fixed in the master. I would be grateful.

**Comment by stevermeister** [comment]
@nonblocking 
thank you for the feedback.

published version 3.0.3 for npm and bower.

> It can easily be fixed by naming the attribute "data-disabled" instead of "disabled" (in ng-wig-plugin-adapter.component.js).

you are more than welcome to make a PR for it :)

**Comment by bampakoa** [comment]
@nonblocking are you referring to the **formats** plugin only or to all of them?

**Comment by nonblocking** [comment]
Well, I just tried the formats plugin, but it might concern all plugins, since IE recognises the _disabled_ attribute on all kind of elements (see https://msdn.microsoft.com/en-us/library/ms533732(v=vs.85).aspx). And everything but "false" seems to be treated as true.

**Comment by bampakoa** [comment]
@nonblocking I double checked and the issue appears in the **formats** plugin only. Could it be a problem with `select `element specifically?

**Comment by nonblocking** [comment]
Buttons within a plugin are also somehow grayed out, but they accept user input. Since the _disabled_ attribute outside of form controls is non-standardized I'm not surprised that the behaviour is inconsistent.

I'd suggest to prefix **all** attributes to avoid such problems.

**Comment by stevermeister** [comment]
looks pretty ok for me:
IE9
![screen shot 2016-11-25 at 16 01 39](https://cloud.githubusercontent.com/assets/1526680/20629283/f98aed22-b32a-11e6-889e-859520a95325.png)

IE10
![screen shot 2016-11-25 at 16 00 45](https://cloud.githubusercontent.com/assets/1526680/20629290/007352b4-b32b-11e6-87ce-d07c8b72f5dd.png)

IE11
![screen shot 2016-11-25 at 16 01 16](https://cloud.githubusercontent.com/assets/1526680/20629296/0825665a-b32b-11e6-818e-3e75c938ca62.png)


Chrome
![screen shot 2016-11-25 at 16 01 49](https://cloud.githubusercontent.com/assets/1526680/20629298/0bede3b6-b32b-11e6-8db7-8d943ba7e1f2.png)
