### ISSUE TITLE
ng-wig2+ - Angular1.3+

### ISSUE THREAD

**Issue by optikool** [stevermeister/ngWig#145]
Hi, 

Your readme file states there is a ng-wig2+ for Angular1.3+. Where can I find this version as I am not using Angular 1.5 and cannot upgrade to this version?

Thanks!

**Comment by stevermeister** [comment]
Hi @optikool ,

I think you can try to use this version - https://github.com/stevermeister/ngWig/tree/v2.3.7
that is latest for Angular1.3

**Comment by optikool** [comment]
Excellent! I'll give it a try. Thanks. :+1:

**Comment by smlshn** [comment]
Hi @optikool I'm still getting this error

ng-wig.js:145 Uncaught TypeError: angular.module(...).component is not a function(anonymous function) @ ng-wig.js:145
angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=myapp&p1=Error%3A%2…okPro%2FDesktop%2FngWig-2.3.7%2Fdist%2Fangular%2Fangular.min.js%3A19%3A463)

 ('am using angular v1.4.8

**Comment by smlshn** [comment]
I again removing 
angular.module('ngWig')
  .component('ngWigPlugin', {
    bindings: {
      plugin: '<'
    },
    controller: function($scope, $element, $compile) {
      $element.replaceWith($compile('<' + this.plugin.pluginName + ' />')($scope));
    }
  });
at line 144 in ng-wig.js the problem gone is that safe? :)

**Comment by stevermeister** [comment]
version v2.3.7 does not have components, please use correct version

please use this version - https://github.com/stevermeister/ngWig/tree/v2.3.7 to have back compatibility with Angular < 1.5
