### ISSUE TITLE
adding link on mozilla don't work

### ISSUE THREAD

**Issue by alainib** [stevermeister/ngWig#147]
I'm getting a strange behavior on mozilla ( version 48.0.1 on windows 7 )

The link button open the popup, i paste for example "www.google.com" but when i click "ok" the popup close nut nothink is added in the text. no link !

It work on my chrome but not on mozilla.
any advice please ?

**Comment by stevermeister** [comment]
@alainib 
you should select text first, which you want to make a link

**Comment by bampakoa** [comment]
@alainib What version of ngWig are you using?

**Comment by alainib** [comment]
@stevermeister oooh yeah it work this way on mozilla. On chrome you can just create a link without selecting text before. 
@bampakoa i use the version: 2.3.4 version

**Comment by bampakoa** [comment]
@alainib this has been resolved in the latest version of the library as far as I can tell.You can either upgrade or, if you dont wish to, you can copy paste the appropriate piece of code into your fork.

**Comment by alainib** [comment]
yes thank you. i update angular to 1.5.7 and ng-wig to v3 and now it work. 
please how can make link with 'target="_blank"' ?

**Comment by bampakoa** [comment]
@alainib I am glad you solved it. If there is anything else you would like to ask, please feel free to do so :smile:
