### ISSUE TITLE
Unwanted click on the first button in toolbar

### ISSUE THREAD

**Issue by enricodeleo** [stevermeister/ngWig#154]
Hi everyone,

I just discovered this editor and I really like it. Everything works as expected BUT I'm experiencing a weird behaviour: when I click within the content area the first button of the toolbar is also clicked (no matter which button it is) and the content is altered consequently. Am I doing something wrong? Anyone had the same experience?

**Comment by bampakoa** [comment]
@enricodeleo.

1. How do you setup the editor in html ? 
2. Do you have any plugins active ?
3. Can you provide a plnker with your code?

**Comment by enricodeleo** [comment]
Just fixed myself. The problem was that I used the editor in place of a `<textarea>` in a form using foundation 6 that suggests to put elements between `<label>`. Apparently moving the editor out of the label fixed the error.
