### ISSUE TITLE
Focus on first button when using tab

### ISSUE THREAD

**Issue by LoganDupont** [stevermeister/ngWig#159]
The problem is that we want to use the tab to navigate to the ng-wig but the focus is on the first button and not on the inputfield so the user will not see that the focus is on the ng-wig at that moment.

**Comment by bampakoa** [comment]
@LoganDupont the first focus is on the toolbar for accessibility purposes. Editor buttons have styles attached to them so that it is clear when they are focused.

![image](https://cloud.githubusercontent.com/assets/7170892/21466258/be1e9132-c9cb-11e6-99dd-163f6781e676.png). 

You can always override the style to match your need. I hope that helps!

**Comment by LoganDupont** [comment]
@bampakoa So you want to say that i need to add a focus style to the buttons to get a proper solution for this? Because I think it should be there as default so the person can clearly see that the buttons are focused when you press the tab to switch between the different input-fields. At the moment I don't get the focused border that you show me when I try to press the tab button. 

You can find my example here 
https://codepen.io/anon/pen/ObYmqe

Greets,
Logan

**Comment by bampakoa** [comment]
@LoganDupont Could you please check with version 3.0.9 tag? 

@stevermeister **dist** folder is a bit outdated in **master** branch.

**Comment by LoganDupont** [comment]
So i tried to add the https://cdnjs.cloudflare.com/ajax/libs/ng-wig/3.0.9/ng-wig.js file in my example but i got still the same problem.

You can find my example here:
https://codepen.io/LoganDupont/pen/gLJxQX/

**Comment by bampakoa** [comment]
@LoganDupont your CSS resource still points to the **master** branch.

**Comment by LoganDupont** [comment]
@bampakoa Okay thanks, it solves the problem. I added https://cdnjs.cloudflare.com/ajax/libs/ng-wig/3.0.9/css/ng-wig.css file so there is indeed something wrong with the dist folder in the master branch that is not up to date.

**Comment by stevermeister** [comment]
sorry guys, I was on vacation, give me a moment to dive in it.

**Comment by stevermeister** [comment]
@LoganDupont thank you for you feedback
@bampakoa thx! fixed dist folder, please check

**Comment by LoganDupont** [comment]
@stevermeister I think we can close this one after the links like this https://cdn.rawgit.com/stevermeister/ngWig/master/dist/ng-wig.js are updated :)
