### ISSUE TITLE
Not working with angular 1.6.1

### ISSUE THREAD

**Issue by swilsonsantos** [stevermeister/ngWig#160]
The new version of angular, brings some [breaking changes](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes) related to components.

Previously all the bindings are available in any part of the controller, now you only can access it through the this.$onInit function

Error showed:
TypeError: Cannot read property 'pluginName' of undefined at new angular.module.component.controller (ng-wig.js [sm]:229)

**Comment by stevermeister** [comment]
thank you for the feedback! 
I've deployed the update to fix this issue. Please check

**Comment by bampakoa** [comment]
@stevermeister I think we can close this.
