### ISSUE TITLE
Initial ng-model not displayed if placeholder is used

### ISSUE THREAD

**Issue by hurricane987** [stevermeister/ngWig#162]
Hi! I love your texteditor, but I am having one problem with it. I am using it for a messaging function, and if there is a default string provided for the ng-model, it won't be displayed if the "placeholder" property on ng-wig is used. It's not that big of an issue, because I can conditionally display different ng-wigs based on whether or not there is an initial value for the model, but I thought I'd let you guys know. Thanks again for making such a killer, lightweight texteditor; we're using it all over our application.

**Comment by bampakoa** [comment]
@hurricane987 which version of the editor are you using?

**Comment by hurricane987** [comment]
Was using 3.0.7, but just upgraded to 3.0.14 and the problem is fixed. Hurray!
