### ISSUE TITLE
Placeholder not showing up

### ISSUE THREAD

**Issue by samosale** [stevermeister/ngWig#163]
I added placeholder but it won't show. I have tried several ways of adding placeholder, the last one is with angular interpolation bindings
`        <ng-wig ng-model="$ctrl.noteContent" placeholder="{{ $ctrl.placeholder }}" flex></ng-wig>
`

I am using angular 1.6.0 and ng-wig 3.0.9

**Comment by bampakoa** [comment]
Could you please try with the latest version?

**Comment by sajithk** [comment]
Same here. I tried the latest version at the moment (3.0.16), still not working. any fix?

**Comment by bampakoa** [comment]
@sajithk Can you setup a **plnkr** for this? It seems to be working on the examples that are on the README file.

**Comment by samosale** [comment]
I resolved this issue and the problem was I did not include css ng-wig file.
