### ISSUE TITLE
Editor examples

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngWig#164]
@stevermeister I think it should be better to maintain [examples](https://github.com/stevermeister/ngWig#examples) of the editor in the **gh-pages** branch and avoid using plunkers. Everyone has to remember to update the version of **ngWig** in plunkers that maintains when a new version is released. What do you think about it?

**Comment by stevermeister** [comment]
We are using the latest version on plunker by default, no?
And for gh-pages - it would be really hard to keep them up-to-date.

**Comment by bampakoa** [comment]
Actually no. When a new version is released, I go to my plunkers and update the corresponding links:
e.g. `<script src="https://cdn.rawgit.com/stevermeister/ngWig/v3.0.14/dist/ng-wig.min.js"></script>`. Do you have any suggestion to make it simpler?

**Comment by stevermeister** [comment]
All plunkers that I've created for README contain:

    <script src="//cdn.rawgit.com/stevermeister/ngWig/master/dist/ng-wig.js"></script>

so just **last** version from dist.
