### ISSUE TITLE
Insert Image?

### ISSUE THREAD

**Issue by tkserver** [stevermeister/ngWig#172]
I've seen inserting an image discussed but I see nowhere in the docs which show if this feature actually exists and how to implement it.

**Comment by bampakoa** [comment]
@tkserver You can insert an image from a URL by adding a standard button during configuration of the **ngWigToolbarProvider**.

`ngWigToolbarProvider.addStandardButton('image', 'Insert image', 'insertImage', 'fa-image');`

**Comment by tkserver** [comment]
Thank you @bampakoa
