### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by MacJu** [stevermeister/ngWig#173]
Hello,

I would like to get in touch with you concerning a security issue. 
What is the best way for us to get in contact?

Kind regards,

Justin

**Comment by stevermeister** [comment]
security issue of ngwig?

**Comment by MacJu** [comment]
Hello,

Yes I discovered a XSS vulnerability with ngWig.
I didn't want to publicly disclose it as it can be critical if used in a
production environment.

Justin

Le 28 sept. 2017 21:19, "Stepan Suvorov" <notifications@github.com> a
écrit :

**Comment by LoganDupont** [comment]
I hope this will get fixed as soon as possible. Thanks for reporting this @MacJu

**Comment by stevermeister** [comment]
@MacJu you can contact me via email - stevermeister@gmail.com

**Comment by stevermeister** [comment]
added sanitization section with explanation - https://github.com/stevermeister/ngWig/blob/master/README.md#sanitization

**Comment by LoganDupont** [comment]
@stevermeister I think you shouldn't provide the info how to do xss. Now you gave people with bad intentions the info they need to manipulate your ngWig. Instead just put a message that this tool has security issues if won't be solved so persons that want to use your tool are aware of this.

**Comment by stevermeister** [comment]
I think that's nice that they can test their implementations, 
but I don't mind to remove the instructions from readme file
