### ISSUE TITLE
How to focus on the container ?

### ISSUE THREAD

**Issue by AdamAnandUS** [stevermeister/ngWig#175]
Hello,

As soon as I load the "ngWig" component, the focus goes to the first button on the toolbar. Instead I want the focus to be on the container so that the user can start typing in right away.

How can I achieve this ? Please suggest.

Thanks
Adam

**Comment by bampakoa** [comment]
@AdamAnandUS Which version do you use?

**Comment by AdamAnandUS** [comment]
I am using -- ngx-wig@0.3.3

**Comment by bampakoa** [comment]
This repo is for AngularJS version of ngWig. You need to open an issue in [this](https://github.com/stevermeister/ngx-wig) repository which is for Angular version.

**Comment by AdamAnandUS** [comment]
Thank you for directing me to the right link. I have opened the issue there. I will close this issue here. Have a great day.
