### ISSUE TITLE
Release 3.0.16 missing

### ISSUE THREAD

**Issue by simonered** [stevermeister/ngWig#176]
Please create release for v3.0.16. Current latest release (3.0.14) has some crucial bugs.

Thank you

**Comment by stevermeister** [comment]
it's already published, no?

**Comment by fairray** [comment]
bower didn't find v 3.0.16
![mint 17 1 - vmware workstation 2017-12-05 16 57 21](https://user-images.githubusercontent.com/12017660/33613644-d2bc5c1e-d9dd-11e7-9160-ed7a5d7d69b8.png)

**Comment by stevermeister** [comment]
I got your point. 
added v3.0.16 tag, now it should work
