### ISSUE TITLE
formats not working in IE

### ISSUE THREAD

**Issue by gronk555** [stevermeister/ngWig#178]
open in IE
https://plnkr.co/edit/TgKThPQjlG4ctzGYk6Kq
see that text type dropdown is disabled

**Comment by bampakoa** [comment]
Related to #132 @stevermeister I can confirm that the problem exists. Is it working for you?

**Comment by stevermeister** [comment]
yes, unfortunately, it's true. but still don't have time to dive into it and fix :(
