### ISSUE TITLE
Insert special characters

### ISSUE THREAD

**Issue by asimakath** [stevermeister/ngWig#18]
It would be great if someone can develop a feature to add special characters as an html entity into the editor. Insert a special character say copyright symbol © in the editor so that the produced HTML is `&#169;`

**Comment by stevermeister** [comment]
@asimakath 
now we have possibility to add plugins, so it would be nice if you could create plugin for this functionality and put into plugins folder

**Comment by stevermeister** [comment]
I'll close it for now
