### ISSUE TITLE
Issue with multiple instances

### ISSUE THREAD

**Issue by bizantom** [stevermeister/ngWig#201]
When several instances of ng-wig are set up on the same page, the button of one of the editor can modify the content of another editor.

How to reproduce:
Here is a plunker with two instances: https://plnkr.co/plunk/Z6YsSzXn0pZ8EF4M
Select some text in the first instance than click on the bold button of the second instance. The selected text of the first instance is now bold.
Moreover the action on a ng-wig instance can modify the content of any node with contentEditable=true...

Expected behavior:
the button of an instance should interact only with the content of this instance.

**Comment by stevermeister** [comment]
@bizantom wow, interesting.

btw, are you still using AngularJS? it's time to migrate to Angular and ngx-wig ;)

**Comment by bizantom** [comment]
@stevermeister Yes still using AngularJS on an old project that does not change a lot. I think it will never be migrated to Angular...
Off course, I am using Angular on most of the other projects! Never have the opportunity to test ngx-wig though...
