### ISSUE TITLE
Unable to push or create PR targeting to upstream

### ISSUE THREAD

**Issue by rommelatienza** [stevermeister/ngWig#210]
I'm receiving authentication failed

**Comment by stevermeister** [comment]
have you tried to do a fork first?
<img width="118" alt="Screenshot 2022-01-03 at 20 08 13" src="https://user-images.githubusercontent.com/1526680/147969724-167babb7-380a-44e1-9cf0-67f8fdc0a05b.png">

**Comment by rommelatienza** [comment]
@stevermeister yes steve, i tried. the latest fork was my PR. can you move that to upstream?

**Comment by rommelatienza** [comment]
@stevermeister 

![image](https://user-images.githubusercontent.com/12545654/148028951-07ef4e8d-867f-4b7f-9c41-a987bd8d21ea.png)

**Comment by rommelatienza** [comment]
@stevermeister 

![image](https://user-images.githubusercontent.com/12545654/148029089-aa9d86dc-cad1-4fd9-b5d4-54e997304433.png)

**Comment by stevermeister** [comment]
I think you are trying to push it directly to the origin, but you don't have to do it - just make PR from your forked version to this one. 
I did not setup any additional permissions to this repository, so it should work in a standard way

**Comment by rommelatienza** [comment]
hi @stevermeister , i just created new PR. can you check it?

**Comment by stevermeister** [comment]
@rommelatienza , you managed to do it! cool! 
checking now...
