### ISSUE TITLE
livereload inserted javascript automatically appended to content.

### ISSUE THREAD

**Issue by ShawnStrickland** [stevermeister/ngWig#27]
I noticed that I'm getting live reload insertion while I'm using grunt within my project.  It'll create data as it should,  and append a `<script>` inside of it all like so:
    `<p><ul><li>kljsdf sdfdfs<br></li></ul><div><br></div><h1>yfd</h1></p><script src=\"http://127.0.0.1:35729/livereload.js?ext=Safari&amp;extver=2.0.9\"></script>`
For any page that I'm inserting this live reload into.

**Comment by stevermeister** [comment]
but it's normal for grunt-watch, right?

**Comment by ShawnStrickland** [comment]
Is it?  Looks like with ngWig, the live reload get's injected twice into the page.  Mind you; it still works correctly but for some reason ngWig will apply it to whatever is created in the WYSIWYG editor.  Does it have to use itself as an `iframe` to work?

**Comment by stevermeister** [comment]
@ShawnStrickland ,
could you check it now please?

we've removed iframe.
