### ISSUE TITLE
IE8, toolbar images not appearing

### ISSUE THREAD

**Issue by bavarod** [stevermeister/ngWig#28]
When I try to use your directive with IE8, the toolbar images donot appear.

I suspect related to IE8 not supporting svg

**Comment by stevermeister** [comment]
Do you really need to support IE8?

**Comment by bavarod** [comment]
Greeting Steve
I'm with you, I wish IE8 would finally disappear.
but, Unfortunately there's still a lot of corporate PC's with XP installed on them.So IE8 is still alive and well.
According to this website (http://www.theie8countdown.com/), IE8 is still making up to 10% of the browsers out there.
Regards Dino
Date: Tue, 27 Jan 2015 11:00:39 -0800

**Comment by stevermeister** [comment]
I'm sorry to hear that you still should support IE8. 
we've already dropped the support of this browser version and now just show the page "You are using old browser" for all our products.

AngularJS dropped support for version 1.3
https://docs.angularjs.org/guide/ie

Even Microsoft is going to do it in one year(together with 9 and 10)
http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx

so I don't see the reason to make such downgrade of my ngWig module.

but you still could make a fork and create you version out of it, without svg.

**Comment by bavarod** [comment]
Greetings Steve
Thanks very much for your feedback.I'll take your suggestion and fork your code.

Regards Dino

Date: Tue, 27 Jan 2015 22:40:28 -0800

**Comment by stevermeister** [comment]
Good Luck with IE! :)
