### ISSUE TITLE
Question about sizing the text area.

### ISSUE THREAD

**Issue by briangullo** [stevermeister/ngWig#30]
Hello,

Had a quick question.  I've tried setting the width and height on ngWig several different ways. It seems like no matter what i do, the change to height, changes the height of the actual text area, but leaves the box the same size, and also causes any form elements under the ngWig to raise and overlap the box.   I've tried setting cols and rows like such:
  <textarea ng-wig="" cols="50" rows="5"></textarea>

and tried changing the style

  <textarea ng-wig="" style="set height here"></textarea>

Any info on what I should do here?

Thanks!
B

**Comment by stevermeister** [comment]
Hi,

if you want to switch off auto expand you should add special attribute:

    data-autoexpand="off" 
and you set width and height:

    <textarea ng-wig="text2" data-autoexpand="off" style="height: 200px; width:500px"></textarea>

**Comment by stevermeister** [comment]
@briangullo ,

we've removed "autoexpand" I new version of editor, so now you could simple set it up with styles (see the demo)

**Comment by dev-quatreepingles** [comment]
Hello @stevermeister 

Sorry to re-open the topic. I find no way to force the height the container (style does not work for example), and no doc or issue seems to talk about that, expected that one.

Is there still a way to do it? I'm using the latest version.

Thank you a lot for your support.
Jourdan

**Comment by stevermeister** [comment]
@dev-quatreepingles could you show us some examples in sandbox what you have tried and what did not work?
