### ISSUE TITLE
ng-maxlength and ng-minlength doesn't work

### ISSUE THREAD

**Issue by mmiseyko** [stevermeister/ngWig#34]
```html
<textarea
      required=true
      name="deal_public_description"
      ng-model="description"
      ng-maxlength=3000
      ng-minlength=300
      cols="30"
      rows="10"
      ng-wig="description"
      data-autoexpand="off"
    >
</textarea>
```

is valid when description = 
<pre>
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0123456789
0
</pre>

155 characters

**Comment by stevermeister** [comment]
hm, when you are going to put html inside how are you going to define amount of characters?

**Comment by stevermeister** [comment]
@mmiseyko ,
could you check it now please?

we've removed iframe from it.

**Comment by cpeele00** [comment]
hello, I can't get ng-maxlength to work either. I love your directive by the way :-) Any help would be greatly appreciated.

**Comment by stevermeister** [comment]
cpeele00,

I ask you to create requirements for it?
Because it's not obvious what should we limit in such manner: source length or wysiwyg length

**Comment by cpeele00** [comment]
Hello! what we need is for the user to not be able to type in more characters than the specified max. If I add maxlength or ng-maxlength it does not prevent the user from entering additional characters like you would expect. Thanks again :-)

**Comment by stevermeister** [comment]
ok, I'll think about such option

**Comment by stevermeister** [comment]
@cpeele00 ,
still did not have time for this issue :(
may be you could provide your ideas in pull request?

source code implementation:
https://github.com/angular/angular.js/blob/291d7c467fba51a9cb89cbeee62202d51fe64b09/src/ng/directive/validators.js#L54

**Comment by stevermeister** [comment]
@mmiseyko , @cpeele00 ,

it's now there in V3
https://github.com/stevermeister/ngWig/tree/v3.0.0-rc2
