### ISSUE TITLE
Issue opening in Ipad

### ISSUE THREAD

**Issue by samarth-rao** [stevermeister/ngWig#35]
Text is going out of the boundary in rich-text in Ipad. Scrollbar is not functioning when opening in Ipad.

**Comment by picitujeromanov** [comment]
doesn't work at all on iphone

**Comment by stevermeister** [comment]
@picitujeromanov ,

could you provide more details please?

**Comment by picitujeromanov** [comment]
Okay I take that one back, after testing default demo I assume that it's an issue on my side.

**Comment by stevermeister** [comment]
let me know if it is not resolved
