### ISSUE TITLE
Icon set

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngWig#50]
Hi,

Could you please point me where did you get your icons from?

**Comment by Velzevul** [comment]
Hi!

I am pretty sure these were custom-made.
But if you are looking for a good resource with icons I could recommend the icomoon app: https://icomoon.io/

**Comment by bampakoa** [comment]
@stevermeister I am asking for the icons as I would like to make a PR for font color button.

**Comment by Velzevul** [comment]
@bampakoa I have just checked - these icons were indeed custom-made, which means there's no place where you could get the matching icon for "font color" button. You can find source .svg icons in the svg-icons-src/ folder.

(I also could try to design one that would match the overall style)

**Comment by bampakoa** [comment]
@Velzevul It would be great if you could design one. Thanks very much.
