### ISSUE TITLE
İs it possible to insert text to editor from angularjs controller when ngwig is in edit mode?

### ISSUE THREAD

**Issue by cimey** [stevermeister/ngWig#51]
Hi,

I want to insert an html image to editor in javascript. How can i achieve that?

**Comment by stevermeister** [comment]
Hi @cimey , 

what do you mean by "html image"?

according to you question in title:
>İs it possible to insert text to editor from angularjs controller

yes, it's possible by changing model

**Comment by cimey** [comment]
Hi @stevermeister , thanks for your reply when i want to add image from controller image is not seen but image html is seen in editor like this "<img src='image.jpeg' />" but if it is added in edit mode image is seen. I want to add html code of image in edit mode . How can i achieve?

**Comment by stevermeister** [comment]
hm, 
could you create jsfiddle for it?
we will see what we could do.

**Comment by cimey** [comment]
![normalmode](https://cloud.githubusercontent.com/assets/7849782/8405735/26da2d72-1e5f-11e5-930d-3d3fb2d89625.jpg)

**Comment by cimey** [comment]
@stevermeister did you understand the problem?

**Comment by cimey** [comment]
@stevermeister  did you understand the problem?

**Comment by stevermeister** [comment]
@cimey ,

could you make jsfiddler/plunker for it?
it would be easy to get into details and fix the issue.
thanks.

**Comment by cimey** [comment]
can you give link of ng-wig.min.js and ng-wig.css?

**Comment by stevermeister** [comment]
you can you this files from dist 
https://github.com/stevermeister/ngWig/tree/master/dist

https://rawgit.com/stevermeister/ngWig/master/dist/css/ng-wig.css
https://rawgit.com/stevermeister/ngWig/master/dist/ng-wig.min.js

**Comment by cimey** [comment]
@stevermeister  create jsfiddle and as you said it is work when add on controller
https://jsfiddle.net/cimey/90s0m25p/5/
