### ISSUE TITLE
underlined text button

### ISSUE THREAD

**Issue by solidismail** [stevermeister/ngWig#55]

**Comment by stevermeister** [comment]
s'il vous plaît
Ctrl + U

**Comment by solidismail** [comment]
Je cherche le bouton (graphique) pour le faire .
Est ce qu'il y a un moyen de l'affiché ?
![capture d ecran 2015-07-08 a 12 26 00](https://cloud.githubusercontent.com/assets/1219754/8568294/c559b954-256c-11e5-812a-be497ebf471e.png)

Merci

**Comment by stevermeister** [comment]
I see, 
in this case you could just make some changes for template to add the button:

    <li class="nw-toolbar__item">
      <button type="button" class="nw-button nw-button--bold" title="Bold" ng-click="execCommand('underline')"></button>
    </li>


could you try this please?

**Comment by stevermeister** [comment]
@solidismail 

we added possibility to add any buttons in very easy way, underline as well

please have a look
https://github.com/stevermeister/ngWig/blob/master/dist/demo.html#L42
