### ISSUE TITLE
copy and paste

### ISSUE THREAD

**Issue by chrismas** [stevermeister/ngWig#59]
When I do copy from a word docs and paste in to the component it keeps all the fonts from the word docs.
Is there a way to disable this kind of behavior?

**Comment by stevermeister** [comment]
ctrl + shift + v 
or 
cmd + shift + v 

let me know if it does not work for you

**Comment by chrismas** [comment]
Many thanks Stepan for your reply.
The shortcut is working.
Is there a way to tell the component to always past the plain text? It 
should be good for me to have a property inside the component for that.


Christian Massironi
Senior Partner
+39 393 9965383
www.zerobytes.it

Il 29/07/15 14:16, Stepan Suvorov ha scritto:

**Comment by stevermeister** [comment]
ok, will think about this option.
just want to keep this editor as simple as possible.

**Comment by sashless** [comment]
maybe provide a onPaste callback to customize the behavior

**Comment by stevermeister** [comment]
@sashless 
how do you see it?

**Comment by sashless** [comment]
Hm sorry, what are you referring to?

**Comment by stevermeister** [comment]
where do you want to see `onPaste ` callback  ?

**Comment by sashless** [comment]
Well from the top of my head... we could fire a ngwig:beforePaste event or
provide a callback using a provider. Actually I need that as well for my
application so I will do something and create a PR in the next days
(probably Monday)

Stepan Suvorov <notifications@github.com> schrieb am Do., 24. Sep. 2015
16:04:

**Comment by stevermeister** [comment]
> I will do something and create a PR in the next days

yes, please, it would be nice to discuss exact solution.

**Comment by sashless** [comment]
i have created a PR to adress this issue

**Comment by sashless** [comment]
This is now released in v2.2.0 and described in https://github.com/stevermeister/ngWig/pull/87. I think this can be closed now :+1:

**Comment by sashless** [comment]
Well, i mean when you copy & paste its still there but now there is a way to tailor the paste behavior to your needs :+1:

**Comment by stevermeister** [comment]
yes, true. 
this one can be closed

**Comment by harellevy** [comment]
what is the onPaste function to pass that paste the plain text of the clipboard?
