### ISSUE TITLE
Cancel link insertion

### ISSUE THREAD

**Issue by gerhardriphagen** [stevermeister/ngWig#60]
When I click the "link" icon
and click cancel on the popup
it inserts "http://" in the text

I expect nothing to happen when I click cancel

**Comment by stevermeister** [comment]
@GerhardRiphagen,

yes, I know about this issue. 
it's already fixed and fix will be provided with next release

**Comment by picitujeromanov** [comment]
also links are clickable, you should attach a listener to 'nw-editor' and prevent default if target is anchor element

**Comment by stevermeister** [comment]
it was fixed with new release 2.0
