### ISSUE TITLE
"Normal text" state doesn't get initialized on style drop-down

### ISSUE THREAD

**Issue by besuhoff** [stevermeister/ngWig#74]
STR:
1. Open page with ng-wig editor
2. Start typing something in visual mode, giving some line breaks
3. Click "HTML source"
Expected:
&lt;p>text1&lt;/p>&lt;p>text2&lt;/p>
Actual:
&lt;div>text1&lt;/div>&lt;div>text2&lt;/div>

**Comment by stevermeister** [comment]
is it still there?
