### ISSUE TITLE
npm install isn't working

### ISSUE THREAD

**Issue by SamGraber** [stevermeister/ngWig#86]
I'm getting a failure when I try to install the ng-wig package through npm. It almost looks like it's trying to run some sort of post-install script and failing on it, but I haven't been able to figure out how to fix it.
The error is as follows:
![image](https://cloud.githubusercontent.com/assets/6878589/10464224/b10d2648-71b6-11e5-9019-36836ad46484.png)

Any help with this would be much appreciated

**Comment by bampakoa** [comment]
@SamGraber Have you installed **grunt**?

**Comment by SamGraber** [comment]
I have grunt install globally on my PC.

**Comment by bampakoa** [comment]
Have you downloaded the latest version? As far as I can tell there was an issue with postInstall in #68 , but it has been removed from package.json.

**Comment by SamGraber** [comment]
This is with the latest version, unfortunately. I looked over the pull request you referenced, and it looks like it *should* be the same issue, so I don't know why I'm still getting it

**Comment by SamGraber** [comment]
Could it be a version issue, since the package version didn't get updated since that PR was merged? Could be npm is still looking at the old package

**Comment by bampakoa** [comment]
Did you downloaded it from github or install it from npm?

**Comment by SamGraber** [comment]
Just an npm install. I want to use it as a dependency for a different library

**Comment by stevermeister** [comment]
@SamGraber 
hm, as far as I see something is wrong with some of the paths according to your screen.

it would be nice if you could debug it, I think it's somewhere in grunt file with path with '.'
I don't have windows machine near, sorry. 

you can try to play with this paths:
https://github.com/stevermeister/ngWig/blob/master/gruntfile.js#L4

**Comment by SamGraber** [comment]
I tried pulling the Repo down locally and then npm installing it from the local folder, and that worked. I still think the problem is with the version that npm is looking at. You can see that it's trying to run a postInstall script above, which is what's breaking, and also what @sashless was trying to fix in PR https://github.com/stevermeister/ngWig/pull/68. The last version bump and publish is before that PR, so I think npm must be serving up an older version of the Repo.

**Comment by sashless** [comment]
yea @SamGraber is right. My fixes done in #68 are not published yet. @stevermeister  You are in need to release a new version and push it to NPM :+1:

**Comment by sashless** [comment]
@SamGraber in the meantime you could use `"ng-wig": "git+ssh://git@github.com:stevermeister/ngWig.git#commit-hash-of-the-commit-you-need"`

**Comment by SamGraber** [comment]
@sashless Thanks. I was consuming it by copying it to a local folder, but this is probably a better short-term solution since I'll want to use npm eventually so I can get updates of the library

**Comment by sashless** [comment]
youre welcome @SamGraber . I use it all the time until PRs are merged and released =)

**Comment by stevermeister** [comment]
new release is there

**Comment by sashless** [comment]
thanks :+1:

**Comment by SamGraber** [comment]
y, thanks

**Comment by stevermeister** [comment]
let me know if it's still a problem

**Comment by SamGraber** [comment]
I tried the install through npm and it works perfectly! Sorry, I should've closed this myself
