### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by tomrainedotcom** [stevermeister/ngWig#92]
@stevermeister I have been using your plug-in, great by the way and love the new feature of the on-paste feature, which I am currently using.

I needed to use the paste feature to check if the text pasted in was UTF-8 encoded, and after reading your documentation and digging through the paste object I noticed that clipboardData is actually in the originalEvent object within the pasteEvent, so rather than pasteEvent.clipboardData.getData('text/plain') it should be pasteEvent.originalEvent.clipboardData.getData('text/plain');

Thanks again.
Tom

**Comment by stevermeister** [comment]
@tomrainedotcom ,

thank you for the feedback! 

let's try to ping @sashless as an author of onPaste extension

**Comment by sashless** [comment]
nice catch @tomrainedotcom , thanks for pointing that out.

**Comment by stevermeister** [comment]
:+1:
