### ISSUE TITLE
Allow for disabling the WYSIWYG

### ISSUE THREAD

**Issue by SamGraber** [stevermeister/ngWig#95]
It would be nice if the consumer could use the `ng-disabled` attribute to show the text editor as disabled. In this case we would want the text-area to be non-editable and the buttons to be always disabled. This would be useful for cases where you want to conditionally enable/disable the editor, or perhaps use the same display for a read-only view.

**Comment by bampakoa** [comment]
Hi,

You could wrap the editor in a **fieldset** element and set the **ng-disabled** property of the fieldset.

**Comment by SamGraber** [comment]
Thanks for the suggestion. I tried it but it doesn't seem to work as I would expect. The buttons don't work, but they still highlight, and the text area doesn't disable. It's possible I could overwrite the styling to remove the highlight when the disable flag is set, but I have no way of properly disabling the text area.

**Comment by bampakoa** [comment]
Could you please share a plunker?

**Comment by SamGraber** [comment]
:+1: Will do shortly

**Comment by SamGraber** [comment]
http://plnkr.co/edit/FZpYbldu9tXHRWplIfdh?p=preview

**Comment by bampakoa** [comment]
@SamGraber I can see your point. Feel free to submit a PR in case @stevermeister wishes to add it as a feature.

**Comment by SamGraber** [comment]
Submitted
